name: eMarry
version: '1.0-SNAPSHOT'
main: me.emojiado.emarry.EMarry
author: Emojiado

commands:
  emarry:
    description: Comando principal de casamiento.
    permission: emarry.reload
  marry:
    description: Comando para enviar solicitud de casamiento.